%% 1. Find beta weights for S-N in the 812langatlas set. 
%%    Technically, we want B* S - B* N, so the contrast image should be used here..
%% 2. Extract voxel level responses across whole brain (or maybe grey matter mask)
%% Last updated: 06/09/2020

addpath('/om/group/evlab/software/evlab17')
evlab17 init
% subjects specified

experiments(1)=struct(...
'pwd1','/mindhive/evlab/u/Shared/SUBJECTS/',...  %SUBJECTS directory
'pwd2', 'firstlevel_speechandlangloc',... %first level directory
'data', {{
    '313_VWFA_03_sess2_PL2017'
    '314_VWFA_13_sess2_PL2017'
    '315_VWFA_17_sess2_PL2017'
}});


localizer_spmfiles={};
effectofinterest_spmfiles={};
i=0;
for nexps=1:length(experiments)
	    for nsub=1:length(experiments(nexps).data)
		       i=i+1;
localizer_spmfiles{i}=fullfile(experiments(nexps).pwd1,experiments(nexps).data{nsub},experiments(nexps).pwd2,'SPM.mat');
effectofinterest_spmfiles{i}=fullfile(experiments(nexps).pwd1,experiments(nexps).data{nsub},experiments(nexps).pwd2,'SPM.mat');
    end
end

ss=struct(...
          'swd',[pwd '/EffectSizes_SWT'],...
          'EffectOfInterest_spm',{effectofinterest_spmfiles},...
          'Localizer_spm',{localizer_spmfiles},...
          'EffectOfInterest_contrasts',{{ ...
           'S' 'N' 'T'
        }},...
          'Localizer_contrasts',{{'S-N'}},...
          'Localizer_thr_type','percentile-ROI-level',...
          'Localizer_thr_p',0.1,...
          'type','mROI',...
          'ManualROIs','/mindhive/evlab/u/Shared/ROIS_Nov2020/Func_Lang_LHRH_SN220/allParcels_language.nii',...
          'overlap_thr_roi',     0,...
          'model',1,...
          'estimation','OLS',...
          'overwrite',true,...
          'ExplicitMasking','',...
          'ask', 'none');

ss=spm_ss_design(ss);
ss=spm_ss_estimate(ss);

