---
title: "R Notebook"
output: html_notebook
---

```{r}
library(ggpubr)
library(tidyverse)
library(readxl)

n1024_SN_data <- read_excel("n1024_effectsizes.xlsx",sheet="SN") %>% mutate(Effect = replace(Effect, Effect == "S", "Language")) %>% mutate(Effect = replace(Effect, Effect == "N", "Control"))

```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Cmd+Option+I*.

```{r}


dots=bind_rows(n1024_SN_data %>% filter(Lateralization=="left-lat", ROI<=6) %>% group_by(Subject, Langloc_Version, Effect) %>% summarise(roi_mean=mean(EffectSize)), n1024_SN_data %>% filter(Lateralization=="right-lat", ROI>6) %>% group_by(Subject, Langloc_Version, Effect) %>% summarise(roi_mean=mean(EffectSize)))
dots$Effect<-factor(dots$Effect, levels = c("Language", "Control"))

bar=dots %>% group_by(Langloc_Version, Effect) %>% summarise(version_effect_mean=mean(roi_mean))
bar$Effect<-factor(bar$Effect, levels = c("Language", "Control"))


ggplot(bar,aes(fill=Effect,x=Langloc_Version,y=version_effect_mean)) + geom_bar(position=position_dodge(.9),stat='identity') + geom_point(data=dots, aes(color=Effect,x=Langloc_Version,y=roi_mean), position=position_dodge(width=.9)) + scale_y_continuous(limits = c(-3, 7)) + ggtitle("Language & control activation estimates across language localizer versions") +xlab("Language Localizer Version") + ylab("BOLD Percent Signal Change") + theme_pubr()


ggsave('SI_conditions_by_langloc.tiff',fig,width=10,height=7)
```

